# Generated by Django 6.1.2 on 2026-10-07 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('title', models.CharField(max_length=160, verbose_name='اسم المشروع')),
                ('category', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='الصورة')),
                ('static_image', models.CharField(blank=True, max_length=180, verbose_name='مسار صورة افتراضية')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='الموقع')),
                ('featured', models.BooleanField(default=False, verbose_name='مشروع مميز')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشروعات',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('title', models.CharField(max_length=120, verbose_name='اسم الخدمة')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='الرابط المختصر')),
                ('short_description', models.CharField(max_length=260, verbose_name='الوصف المختصر')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='الصورة')),
                ('static_image', models.CharField(blank=True, max_length=180, verbose_name='مسار صورة افتراضية')),
                ('accent', models.CharField(default='#d8a63a', max_length=20, verbose_name='لون البطاقة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='مؤسسة الخط النقي للمقاولات والمصاعد', max_length=180, verbose_name='اسم الشركة')),
                ('company_name_en', models.CharField(default='Pure Line for Contracting and Elevators Est.', max_length=180, verbose_name='الاسم بالإنجليزية')),
                ('hero_title', models.CharField(max_length=220, verbose_name='عنوان الواجهة')),
                ('hero_subtitle', models.TextField(verbose_name='وصف الواجهة')),
                ('about_title', models.CharField(max_length=220, verbose_name='عنوان من نحن')),
                ('about_text', models.TextField(verbose_name='نبذة عن الشركة')),
                ('phone_primary', models.CharField(default='0534201283', max_length=20, verbose_name='الهاتف الأول')),
                ('phone_secondary', models.CharField(blank=True, default='0506019745', max_length=20, verbose_name='الهاتف الثاني')),
                ('whatsapp', models.CharField(default='966534201283', max_length=20, verbose_name='رقم واتساب بالصيغة الدولية')),
                ('email', models.EmailField(default='info@pureline.sa', max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(default='المملكة العربية السعودية - خميس مشيط ومكة المكرمة', max_length=250, verbose_name='العنوان')),
                ('commercial_registration', models.CharField(default='4031303184', max_length=40, verbose_name='السجل التجاري')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='الصفة أو القطاع')),
                ('quote', models.TextField(verbose_name='الرأي')),
            ],
            options={
                'verbose_name': 'رأي عميل',
                'verbose_name_plural': 'آراء العملاء',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+() -]{8,20}$', 'أدخل رقم هاتف صحيحًا.')], verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='المدينة / الموقع')),
                ('message', models.TextField(verbose_name='تفاصيل الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'طلب تواصل',
                'verbose_name_plural': 'طلبات التواصل',
                'ordering': ('-created_at',),
            },
        ),
    ]
