# Generated by Django 6.1.2 on 2026-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('title', models.CharField(max_length=80, verbose_name='القيمة')),
                ('description', models.CharField(max_length=240, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'قيمة الشركة',
                'verbose_name_plural': 'قيم الشركة',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('value', models.PositiveIntegerField(verbose_name='الرقم')),
                ('suffix', models.CharField(blank=True, help_text='مثال: % أو +', max_length=12, verbose_name='اللاحقة')),
                ('label', models.CharField(max_length=120, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'رقم وإحصائية',
                'verbose_name_plural': 'الأرقام والإحصائيات',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان الخطوة')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'خطوة عمل',
                'verbose_name_plural': 'خطوات العمل',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.CharField(blank=True, default='السبت - الخميس: 8 صباحًا حتى 6 مساءً', max_length=160, verbose_name='ساعات العمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_text',
            field=models.TextField(default='أرسل تفاصيلك وسيقوم فريقنا بمراجعتها والتواصل معك لتحديد الخطوة الأنسب.', verbose_name='نص قسم التواصل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(default='فكرتك جاهزة لتتحول إلى واقع؟', max_length=220, verbose_name='عنوان قسم التواصل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='حلول المقاولات والمصاعد والأعمال الكهروميكانيكية بمعيار واحد من الجودة.', max_length=300, verbose_name='نص أسفل الموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='رابط الموقع على Google Maps'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='اتركها فارغة لاستخدام صورة التكييف الحالية.', upload_to='brand/', verbose_name='صورة الواجهة الرئيسية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='اتركه فارغًا لاستخدام الشعار الحالي.', upload_to='brand/', verbose_name='شعار الشركة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='وصف محركات البحث'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='عنوان محركات البحث'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sales_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد المبيعات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='snapchat_url',
            field=models.URLField(blank=True, verbose_name='Snapchat'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='x_url',
            field=models.URLField(blank=True, verbose_name='X / Twitter'),
        ),
    ]
